### PR TITLE
Refactor `findImports` using Typescript AST 

### PR DESCRIPTION
**Pull request by AnatoleLucet**

### CODE REVIEW

**Comment by benawad** [comment]
How will this work for stuff like sass imports?

Do we want to conditionally do a regex/ast?

**Comment by benawad** [comment]
Also would interesting to run this on a medium/large codebase and see the performance difference compared to regex.

**Comment by AnatoleLucet** [comment]
In my opinion we should drop the regex (except if a language doesn't have an available and maintained AST).
For css pre-processors we could use something like [sast](https://github.com/shawnbot/sast). It will certainly increase the number of dependencies that we need but, with a good AST we're sure that we don't catch a commented import or things like such...

To detect which AST to use we could simply conditionally chose it by the given file extension (Typescript's AST for `.js`, `.ts`, etc... Sast for `scss`, `sass`, etc...).

Using an AST could also improve the way we re-write imports. For example, with Sast you can parse the css-like file using `sast.parse()`, then modify what you want in the returned AST tree, and finally stringify back the AST using `sast.stringify()`.

>Also would interesting to run this on a medium/large codebase and see the performance difference compared to regex.

I'm sure that using ASTs will make Destiny slower, but it'll also make it a lot more robust.
One option to not loose too much perfs would be to fork (for example) Typescript's AST, and only keep the parts that we need (ignore comments, ignore strings content, detect all kind of imports, etc...). With that Destiny should stay fast (since the AST doesn't need to parse the whole file in a three) and has a solid way to detect imports.

**Comment by AnatoleLucet** [comment]
That would require a lot a work btw

**Comment by benawad** [comment]
I'm all for Destiny being more robust, but I'm not sure the complexity + performance hit is a worth tradeoff.

That's why I was curious to run this so I can get a better idea of how much slower it would be.

The edge cases for the regex have been pretty niche so far, and I'd rather try to improve our regex first (although if there is something common that comes up that regex can't handle then I might be more inclined towards using an ast).

**Comment by AnatoleLucet** [comment]
> I'm all for Destiny being more robust, but I'm not sure the complexity + performance hit is a worth tradeoff.

Yes, it's true that either the time spent reworking some ASTs or the perf loss by using a plain AST would probably not be worth it...

**Comment by AnatoleLucet** [comment]
Ok, so yes, the perf loss is HUGE with this pr.
I tested Destiny on the `lib` folder in typescript's repo to test how much it will take to parse and find imports in enormous files like these.

The result:
- Using regex is took `808ms`
- Using Typescript's AST it took `3517ms`

**Comment by AnatoleLucet** [comment]
I'll remove the refactoring I made in the `findImports` function from this pr and only keep the tests because there are still useful even with the regex.

**Pull request merged**
