### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by moranje**
Added quotes for globbing to work

### CODE REVIEW

**Comment by sQVe** [comment]
What OS are you on? It works fine on my system without quotes.

**Comment by moranje** [comment]
MacOS. :)

---
Martien

**Comment by AnatoleLucet** [comment]
I needed to use quotes on Ubuntu 19.x with Zsh.

**Comment by moranje** [comment]
Ah yes, I use Zsh as well/

---
Martien

**Pull request merged**
