### PR TITLE
WIP: Code cleanup 02

### PR DESCRIPTION
**Pull request by waynevanson**
Please don't review yet.

### CODE REVIEW

**Comment by waynevanson** [comment]
Is anyone able to check out the CI tests and find out why it wouldn't be working?

I'm not sure why the CI tests failed. On my Ubuntu machine, it passes.

Error looks like something to do with gzip: unexpected end of file.

**Comment by sQVe** [comment]
@waynevanson It failed due to GitHub Actions internals. I reran the tests and they passed.

You should probably do something about your commits though. There is currently 58 commits in this PR and it changes few LOCs.

**Comment by waynevanson** [comment]
@sQVe Thank goodness! Sorry for the delay.

What's happened is that this pull is all of the commits from pull #62 + any additional commits I've made here. I'm unfamiliar with all the good git commands, so I'm sure there is something I could do in future to avoid this.

For this particular pull, should I combine all commits from the previous pull into a single and leave the rest? Is this even possible? If not, what would you recommend?

**Comment by sQVe** [comment]
I would create a new branch at `code_cleanup_02` as a backup and then squash all commits in this branch. There are some conflicts that must be resolved now due to changes that has happened since your made this PR.

**Comment by waynevanson** [comment]
I'm so sorry. I've got no idea what I'm doing regarding the git squashing etc.

I think what I will do is keep the changes I've made elsewhere, refork the branch and create small pull requests from there.

**Pull request closed without merging**
